### PR TITLE
Make things db url based.

### PR DESCRIPTION
**Pull request by mfine**
I've ripped out the `host`, `name`, `user` in favor of taking a db url. The url is more convenient and less error prone and beats having to enter the password in repeatedly. Obviously not a general solution, but would be nice to support urls in addition to the current path.

### CODE REVIEW

**Comment by cbbrowne** [comment]
+1 on this; I'm finding that this is a very much preferable way to handle database connections.

FYI, I'd commend the idea of recommending use of .pgpass to eliminate entering passwords frequently.

**Comment by mbryzek** [comment]
This looks great and thanks so much for contributing!

Would you be open if we changed this patchset to support url or the old style of arguments? I'm a bit hesitant to make a breaking change in the CLI.

we also need to add a couple tests to make sure the parameters parse.

**Comment by mfine** [comment]
Ha, yeah wasn't intending to bring this is as is. The required arguments stuff looked pretty baked in, and after briefly looking through didn't see a quick way to have differing sets of required arguments. Any thoughts on how all that preconditions stuff should be extended?

**Comment by mbryzek** [comment]
I've opened a pull request with an alternative implementation:

https://github.com/mbryzek/schema-evolution-manager/pull/22

This patch adds support for a --url flag to both sem-init and sem-apply - would love if you might take a quick look before we merge - thanks!

**Comment by mbryzek** [comment]
Implemented as #22

**Pull request closed without merging**
